export const categories = [
  { id: "1", name: "Dairy", color: "#FFE2A6" },
  { id: "2", name: "Bakery", color: "#C9A98D" },
  { id: "3", name: "Fruits", color: "#FFCC80" },
  { id: "4", name: "Vegetables", color: "#DBE098" },
  { id: "5", name: "Meat", color: "#F69F95" },
  { id: "6", name: "Beverages", color: "#CD8DE8" },
  { id: "7", name: "Snacks", color: "#FFAF6E" },
  { id: "8", name: "Household", color: "#B19F9A" },
  { id: "9", name: "Personal Care", color: "#FFA9BA" },
  { id: "10", name: "Other", color: "#DSEDF8" },
];

export const shoppingItems = [
  {
    id: "1",
    name: "Milk",
    imageUrl: "",
    quantity: 2,
    category: "Dairy",
    comment: "Low-fat, 1 litre each, prefer brand A",
  },
  {
    id: "2",
    name: "Bread",
    imageUrl: "",
    quantity: 1,
    category: "Bakery",
    comment: "Whole grain, large loaf, no seeds",
  },
  {
    id: "3",
    name: "Apples",
    imageUrl: "",
    quantity: 6,
    category: "Fruits",
    comment: "Organic, medium size, prefer Gala variety",
  },
  {
    id: "4",
    name: "Carrots",
    imageUrl: "",
    quantity: 5,
    category: "Vegetables",
    comment: "Fresh, large size, from local farm if possible",
  },
  {
    id: "5",
    name: "Chicken Breast",
    imageUrl: "",
    quantity: 3,
    category: "Meat",
    comment: "Boneless, skinless, around 200g each",
  },
  {
    id: "6",
    name: "Orange Juice",
    imageUrl: "",
    quantity: 2,
    category: "Beverages",
    comment: "No pulp, 1.5 litres each, prefer brand B",
  },
  {
    id: "7",
    name: "Chips",
    imageUrl: "",
    quantity: 1,
    category: "Snacks",
    comment: "Salted, large bag, prefer brand C",
  },
  {
    id: "8",
    name: "Dish Soap",
    imageUrl: "",
    quantity: 1,
    category: "Household",
    comment: "Lemon scented, 500ml, eco-friendly",
  },
  {
    id: "9",
    name: "Shampoo",
    imageUrl: "",
    quantity: 1,
    category: "Personal Care",
    comment: "For dry hair, 250ml, prefer brand D",
  },
  {
    id: "10",
    name: "Paper Towels",
    imageUrl: "",
    quantity: 2,
    category: "Household",
    comment: "Extra absorbent, 6 rolls each pack, prefer brand E",
  },
];
