export const shoppingItems = [
  {
    id: "1",
    name: "milk",
    imageUrl:
      // "https://images.unsplash.com/photo-1641320785764-17cd1ab58a42?w=800&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NXx8Y2FydG9ufGVufDB8fDB8fHwy",
      "milk_alnatura.png",
    quantity: 2,
    category: "Dairy products",
    comment: "carton, 1 litre, organic, preferably Alnatura Vollmilch",
    isPurchased: false,
  },
  {
    id: "2",
    name: "bread",
    imageUrl:
      // "https://images.unsplash.com/photo-1590301157172-7ba48dd1c2b2?w=800&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MjB8fGJyZWFkfGVufDB8fDB8fHwy",
      "bread.png",
    quantity: 1,
    category: "Bakery products",
    comment: "whole grain, large loaf, no seeds",
    isPurchased: false,
  },
  {
    id: "3",
    name: "apples",
    imageUrl: "apples.png",
    quantity: 6,
    category: "Fruit",
    comment: "organic, medium size, prefer Gala variety",
    isPurchased: false,
  },
  {
    id: "4",
    name: "carrots",
    imageUrl:
      // "https://images.unsplash.com/photo-1511448799201-28c098eb6004?w=700&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTd8fGNhcnJvdHN8ZW58MHx8MHx8fDI%3D",
      "carrots.png",
    quantity: 5,
    category: "Veggies",
    comment: "fresh, large size, from local farm if possible",
    isPurchased: false,
  },
  {
    id: "5",
    name: "chicken breast",
    imageUrl: "chicken-breast.png",
    quantity: 3,
    category: "Meat",
    comment: "boneless, skinless, around 200g each",
    isPurchased: false,
  },
  {
    id: "6",
    name: "orange juice",
    imageUrl: "orange-juice.png",
    quantity: 2,
    category: "Drinks",
    comment: "no pulp, 1.5 litres each, prefer brand B",
    isPurchased: false,
  },
  {
    id: "7",
    name: "crisps",
    imageUrl: "crisps.png",
    quantity: 1,
    category: "Snacks",
    comment: "salted, large bag, prefer brand C",
    isPurchased: false,
  },
  {
    id: "8",
    name: "dish soap",
    imageUrl: "dish-soap.png",
    quantity: 1,
    category: "Household",
    comment: "lemon scented, 500ml, eco-friendly",
    isPurchased: false,
  },
  {
    id: "9",
    name: "shampoo",
    imageUrl:
      // "https://images.unsplash.com/photo-1701992678972-d5a053ad0fb0?q=80&w=2457&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
      "shampoo.png",
    quantity: 1,
    category: "Personal Care",
    comment: "for dry hair, 250ml, prefer brand D",
    isPurchased: false,
  },
  {
    id: "10",
    name: "paper towels",
    imageUrl: "paper-towels.png",
    quantity: 2,
    category: "Household",
    comment: "extra absorbent, 6 rolls each pack, prefer brand E",
    isPurchased: false,
  },
];
