export const shoppingItems = [
  {
    id: "1",
    name: "milk",
    imageUrl: "milk_katt-galvan-LlwDzzc4LN4-unsplash.png",
    // "https://images.unsplash.com/photo-1641320785764-17cd1ab58a42?w=800&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NXx8Y2FydG9ufGVufDB8fDB8fHwy",
    quantity: 2,
    category: "Dairy products",
    comment: "carton, 1 litre, barista oat milk, Coach Jessica's favourite",
    isPurchased: false,
  },
  {
    id: "2",
    name: "bread",
    imageUrl: "bread_vicky-ng-yL9qjDDmmMU-unsplash.png",
    // "https://images.unsplash.com/photo-1590301157172-7ba48dd1c2b2?w=800&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MjB8fGJyZWFkfGVufDB8fDB8fHwy",

    quantity: 1,
    category: "Bakery products",
    comment: "whole grain, large loaf, no seeds",
    isPurchased: false,
  },
  {
    id: "3",
    name: "apples",
    imageUrl: "apples_emma-van-sant---LA23QAzaM-unsplash.png",
    // "https://images.unsplash.com/photo-1504101834554-f30a0054199d?q=80&w=2785&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    quantity: 6,
    category: "Fruit",
    comment: "organic, medium size, prefer Gala variety",
    isPurchased: false,
  },
  {
    id: "4",
    name: "carrots",
    imageUrl: "carrots_free.png",
    // "https://images.unsplash.com/photo-1511448799201-28c098eb6004?w=700&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTd8fGNhcnJvdHN8ZW58MHx8MHx8fDI%3D",
    quantity: 5,
    category: "Veggies",
    comment: "fresh, medium size, from local farm if possible",
    isPurchased: false,
  },
  {
    id: "5",
    name: "chicken breast",
    imageUrl: "chicken-breast_Philippe-Zuber_unsplash.png",
    // "https://images.unsplash.com/photo-1633096013004-e2cb4023b560?w=700&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8Y2hpY2tlbiUyMGJyZWFzdHxlbnwwfHwwfHx8Mg%3D%3D",
    quantity: 3,
    category: "Meat",
    comment: "boneless, skinless, around 200g each",
    isPurchased: false,
  },
  {
    id: "6",
    name: "orange juice",
    imageUrl: "orange-juice_free_unsplash.png",
    // "https://upload.wikimedia.org/wikipedia/commons/thumb/0/05/Orangejuice.jpg/440px-Orangejuice.jpg",
    quantity: 2,
    category: "Drinks",
    comment: "no pulp, 1.5 litres each, prefer brand B",
    isPurchased: false,
  },
  {
    id: "7",
    name: "crisps",
    imageUrl: "crisps_free.png",
    // "https://images.unsplash.com/photo-1579384264577-79580c9d3a36?w=700&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTJ8fHBvdGF0byUyMGNoaXBzfGVufDB8fDB8fHwy",
    quantity: 1,
    category: "Snacks",
    comment: "Coach Andrea's favourite mixed veggie crisps",
    isPurchased: false,
  },
  {
    id: "8",
    name: "dish soap",
    imageUrl: "dish-soap_free.png",
    // "https://upload.wikimedia.org/wikipedia/commons/1/1d/Fit-Spuelmittel.jpg",
    quantity: 1,
    category: "Household",
    comment: "lemon scented, 500ml, eco-friendly",
    isPurchased: false,
  },
  {
    id: "9",
    name: "shampoo",
    imageUrl: "shampoo_free.png",
    // "https://images.unsplash.com/photo-1701992678972-d5a053ad0fb0?q=80&w=2457&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    quantity: 1,
    category: "Personal Care",
    comment: "for dry hair, 250ml, prefer brand D",
    isPurchased: false,
  },
  {
    id: "10",
    name: "paper towels",
    imageUrl: "paper-towels_free.png",
    // "https://images.unsplash.com/photo-1550963295-019d8a8a61c5?w=700&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTN8fHBhcGVyJTIwdG93ZWxzfGVufDB8fDB8fHwy",
    quantity: 2,
    category: "Household",
    comment: "extra absorbent, 6 rolls each pack, prefer brand E",
    isPurchased: false,
  },
];
