export const shoppingItems = [
  {
    id: "1",
    name: "milk",
    imageUrl: "milk_alnatura.png",
    quantity: 2,
    category: "Dairy products",
    comment: "carton, 1 litre, organic, preferably Alnatura Vollmilch",
    isPurchased: false,
  },
  {
    id: "2",
    name: "bread",
    imageUrl: "bread.png",
    quantity: 1,
    category: "Bakery products",
    comment: "whole grain, large loaf, no seeds",
    isPurchased: false,
  },
  {
    id: "3",
    name: "apples",
    imageUrl: "apples.png",
    quantity: 6,
    category: "Fruit",
    comment: "organic, medium size, prefer Gala variety",
    isPurchased: false,
  },
  {
    id: "4",
    name: "carrots",
    imageUrl: "carrots.png",
    quantity: 5,
    category: "Veggies",
    comment: "fresh, large size, from local farm if possible",
    isPurchased: false,
  },
  {
    id: "5",
    name: "chicken breast",
    imageUrl: "chicken-breast.png",
    quantity: 3,
    category: "Meat",
    comment: "boneless, skinless, around 200g each",
    isPurchased: false,
  },
  {
    id: "6",
    name: "orange juice",
    imageUrl: "orange-juice.png",
    quantity: 2,
    category: "Drinks",
    comment: "no pulp, 1.5 litres each, prefer brand B",
    isPurchased: false,
  },
  {
    id: "7",
    name: "crisps",
    imageUrl: "crisps.png",
    quantity: 1,
    category: "Snacks",
    comment: "salted, large bag, prefer brand C",
    isPurchased: false,
  },
  {
    id: "8",
    name: "dish soap",
    imageUrl: "dish-soap.png",
    quantity: 1,
    category: "Household",
    comment: "lemon scented, 500ml, eco-friendly",
    isPurchased: false,
  },
  {
    id: "9",
    name: "shampoo",
    imageUrl: "shampoo.png",
    quantity: 1,
    category: "Personal Care",
    comment: "for dry hair, 250ml, prefer brand D",
    isPurchased: false,
  },
  {
    id: "10",
    name: "paper towels",
    imageUrl: "paper-towels.png",
    quantity: 2,
    category: "Household",
    comment: "extra absorbent, 6 rolls each pack, prefer brand E",
    isPurchased: false,
  },
];
